# Generated by Django 4.2 on 2023-04-12 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
