# Generated by Django 4.2 on 2023-04-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_files_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='files',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='files',
            name='signers',
            field=models.IntegerField(null=True),
        ),
    ]
