# Generated by Django 4.2 on 2023-04-15 06:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_files_completed_files_signers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='wallet',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.files')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
    ]
